name: Generate terraform docs

on:
  pull_request:
    paths:
      - ".github/workflows/**.yml"
      - ".github/workflows/**.yaml"
      - "**.tf*"

jobs:
  docs:
    uses: AhiruMarsh/actions/.github/workflows/generate-terraform-docs.yaml@main
    with:
      working-dir: terraform/
    permissions:
      contents: write
